import os
import sys

# Ensure project root is in path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR not in sys.path:
    sys.path.append(BASE_DIR)

from rag_engine import UAVRAGEngine

def test_in_domain():
    print("\n=== RUNNING TEST 1: In-Domain Test ===")
    query = "What is the RTL procedure when GPS is lost?"
    print(f"Query: '{query}'")
    
    # We will use the fastest available model to run tests if needed, or default
    engine = UAVRAGEngine()
    answer, chunks, latency = engine.query(query)
    
    print("\nAnswer generated by model:")
    print(answer)
    print("\nRetrieved Chunks:")
    for c in chunks:
        print(f"- {c['filename']} (Score: {c['score']:.4f})")

    # Assertions
    # 1. Did it retrieve failsafe_protocols.md?
    retrieved_failsafe = any("failsafe_protocols.md" in c["filename"] for c in chunks)
    assert retrieved_failsafe, "Error: failsafe_protocols.md was not retrieved!"
    print("Assertion Passed: Correct document (failsafe_protocols.md) retrieved.")

    # 2. Did the answer mention AltHold or Altitude Hold?
    # Because when GPS is lost, RTL is not possible and it falls back to AltHold
    assert "althold" in answer.lower() or "altitude hold" in answer.lower() or "failsafe_protocols.md" in answer, \
        "Error: Answer does not mention AltHold or cite failsafe_protocols.md correctly!"
    print("Assertion Passed: Response contains correct fallback mode or citation.")
    
    print("Test 1 Passed Successfully!")

def test_out_of_domain():
    print("\n=== RUNNING TEST 2: Out-of-Domain (Hallucination) Test ===")
    query = "How do I change oil on a diesel engine?"
    print(f"Query: '{query}'")
    
    engine = UAVRAGEngine()
    answer, chunks, latency = engine.query(query)
    
    print("\nAnswer generated by model:")
    print(answer)
    
    # Assertions
    expected_refusal = "i do not have sufficient field documentation to answer this question"
    assert expected_refusal in answer.lower(), \
        f"Error: Model did not refuse to answer correctly. Answer was: {answer}"
    print("Assertion Passed: Model successfully refused to answer out-of-domain query.")
    print("Test 2 Passed Successfully!")

def main():
    print("Starting Automated RAG Test Suite...")
    try:
        test_in_domain()
        test_out_of_domain()
        print("\nAll tests passed successfully!")
    except AssertionError as e:
        print(f"\nTEST SUITE FAILED: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\nTEST SUITE ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
